// Code generated by protoc-gen-go. DO NOT EDIT.
// source: word_search_system_grpc.proto

package wordsearchsystemgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type SearchWordRequest struct {
	KeyWord              string   `protobuf:"bytes,1,opt,name=keyWord,proto3" json:"keyWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchWordRequest) Reset()         { *m = SearchWordRequest{} }
func (m *SearchWordRequest) String() string { return proto.CompactTextString(m) }
func (*SearchWordRequest) ProtoMessage()    {}
func (*SearchWordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{0}
}

func (m *SearchWordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchWordRequest.Unmarshal(m, b)
}
func (m *SearchWordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchWordRequest.Marshal(b, m, deterministic)
}
func (m *SearchWordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchWordRequest.Merge(m, src)
}
func (m *SearchWordRequest) XXX_Size() int {
	return xxx_messageInfo_SearchWordRequest.Size(m)
}
func (m *SearchWordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchWordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchWordRequest proto.InternalMessageInfo

func (m *SearchWordRequest) GetKeyWord() string {
	if m != nil {
		return m.KeyWord
	}
	return ""
}

// The response message containing the greetings
type SearchWordReply struct {
	Matches              []string `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchWordReply) Reset()         { *m = SearchWordReply{} }
func (m *SearchWordReply) String() string { return proto.CompactTextString(m) }
func (*SearchWordReply) ProtoMessage()    {}
func (*SearchWordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{1}
}

func (m *SearchWordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchWordReply.Unmarshal(m, b)
}
func (m *SearchWordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchWordReply.Marshal(b, m, deterministic)
}
func (m *SearchWordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchWordReply.Merge(m, src)
}
func (m *SearchWordReply) XXX_Size() int {
	return xxx_messageInfo_SearchWordReply.Size(m)
}
func (m *SearchWordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchWordReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchWordReply proto.InternalMessageInfo

func (m *SearchWordReply) GetMatches() []string {
	if m != nil {
		return m.Matches
	}
	return nil
}

type AddWordsRequest struct {
	Words                []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWordsRequest) Reset()         { *m = AddWordsRequest{} }
func (m *AddWordsRequest) String() string { return proto.CompactTextString(m) }
func (*AddWordsRequest) ProtoMessage()    {}
func (*AddWordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{2}
}

func (m *AddWordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWordsRequest.Unmarshal(m, b)
}
func (m *AddWordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWordsRequest.Marshal(b, m, deterministic)
}
func (m *AddWordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWordsRequest.Merge(m, src)
}
func (m *AddWordsRequest) XXX_Size() int {
	return xxx_messageInfo_AddWordsRequest.Size(m)
}
func (m *AddWordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWordsRequest proto.InternalMessageInfo

func (m *AddWordsRequest) GetWords() []string {
	if m != nil {
		return m.Words
	}
	return nil
}

type AddWordsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWordsReply) Reset()         { *m = AddWordsReply{} }
func (m *AddWordsReply) String() string { return proto.CompactTextString(m) }
func (*AddWordsReply) ProtoMessage()    {}
func (*AddWordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{3}
}

func (m *AddWordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWordsReply.Unmarshal(m, b)
}
func (m *AddWordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWordsReply.Marshal(b, m, deterministic)
}
func (m *AddWordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWordsReply.Merge(m, src)
}
func (m *AddWordsReply) XXX_Size() int {
	return xxx_messageInfo_AddWordsReply.Size(m)
}
func (m *AddWordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddWordsReply proto.InternalMessageInfo

type Top5SearchKeyWordsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Top5SearchKeyWordsRequest) Reset()         { *m = Top5SearchKeyWordsRequest{} }
func (m *Top5SearchKeyWordsRequest) String() string { return proto.CompactTextString(m) }
func (*Top5SearchKeyWordsRequest) ProtoMessage()    {}
func (*Top5SearchKeyWordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{4}
}

func (m *Top5SearchKeyWordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Top5SearchKeyWordsRequest.Unmarshal(m, b)
}
func (m *Top5SearchKeyWordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Top5SearchKeyWordsRequest.Marshal(b, m, deterministic)
}
func (m *Top5SearchKeyWordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Top5SearchKeyWordsRequest.Merge(m, src)
}
func (m *Top5SearchKeyWordsRequest) XXX_Size() int {
	return xxx_messageInfo_Top5SearchKeyWordsRequest.Size(m)
}
func (m *Top5SearchKeyWordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Top5SearchKeyWordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Top5SearchKeyWordsRequest proto.InternalMessageInfo

type Top5SearchKeyWordsReply struct {
	Keywords             []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Top5SearchKeyWordsReply) Reset()         { *m = Top5SearchKeyWordsReply{} }
func (m *Top5SearchKeyWordsReply) String() string { return proto.CompactTextString(m) }
func (*Top5SearchKeyWordsReply) ProtoMessage()    {}
func (*Top5SearchKeyWordsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ae0e577dd3a98ef, []int{5}
}

func (m *Top5SearchKeyWordsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Top5SearchKeyWordsReply.Unmarshal(m, b)
}
func (m *Top5SearchKeyWordsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Top5SearchKeyWordsReply.Marshal(b, m, deterministic)
}
func (m *Top5SearchKeyWordsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Top5SearchKeyWordsReply.Merge(m, src)
}
func (m *Top5SearchKeyWordsReply) XXX_Size() int {
	return xxx_messageInfo_Top5SearchKeyWordsReply.Size(m)
}
func (m *Top5SearchKeyWordsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_Top5SearchKeyWordsReply.DiscardUnknown(m)
}

var xxx_messageInfo_Top5SearchKeyWordsReply proto.InternalMessageInfo

func (m *Top5SearchKeyWordsReply) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchWordRequest)(nil), "wordsearchsystemgrpc.SearchWordRequest")
	proto.RegisterType((*SearchWordReply)(nil), "wordsearchsystemgrpc.SearchWordReply")
	proto.RegisterType((*AddWordsRequest)(nil), "wordsearchsystemgrpc.AddWordsRequest")
	proto.RegisterType((*AddWordsReply)(nil), "wordsearchsystemgrpc.AddWordsReply")
	proto.RegisterType((*Top5SearchKeyWordsRequest)(nil), "wordsearchsystemgrpc.Top5SearchKeyWordsRequest")
	proto.RegisterType((*Top5SearchKeyWordsReply)(nil), "wordsearchsystemgrpc.Top5SearchKeyWordsReply")
}

func init() { proto.RegisterFile("word_search_system_grpc.proto", fileDescriptor_1ae0e577dd3a98ef) }

var fileDescriptor_1ae0e577dd3a98ef = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xcf, 0x2f, 0x4a,
	0x89, 0x2f, 0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0x88, 0x2f, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0x8d, 0x4f,
	0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x01, 0x49, 0x43, 0x64, 0x21,
	0x92, 0x20, 0x39, 0x25, 0x5d, 0x2e, 0xc1, 0x60, 0xb0, 0x58, 0x78, 0x7e, 0x51, 0x4a, 0x50, 0x6a,
	0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x04, 0x17, 0x7b, 0x76, 0x6a, 0x25, 0x48, 0x44, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x55, 0xd2, 0xe6, 0xe2, 0x47, 0x56, 0x5e, 0x90, 0x53, 0x09,
	0x52, 0x9c, 0x9b, 0x58, 0x92, 0x9c, 0x91, 0x5a, 0x2c, 0xc1, 0xa8, 0xc0, 0x0c, 0x52, 0x0c, 0xe5,
	0x2a, 0xa9, 0x73, 0xf1, 0x3b, 0xa6, 0xa4, 0x80, 0x54, 0x16, 0xc3, 0x4c, 0x16, 0xe1, 0x62, 0x05,
	0x3b, 0x03, 0xaa, 0x14, 0xc2, 0x51, 0xe2, 0xe7, 0xe2, 0x45, 0x28, 0x2c, 0xc8, 0xa9, 0x54, 0x92,
	0xe6, 0x92, 0x0c, 0xc9, 0x2f, 0x30, 0x85, 0x58, 0xe5, 0x0d, 0xb1, 0x1b, 0x66, 0x86, 0x92, 0x29,
	0x97, 0x38, 0x36, 0x49, 0x90, 0x5b, 0xa4, 0xb8, 0x38, 0xb2, 0x53, 0x2b, 0x91, 0x6d, 0x80, 0xf3,
	0x8d, 0x8e, 0x30, 0x71, 0x09, 0x80, 0x94, 0x42, 0xf4, 0x05, 0x83, 0x83, 0x40, 0x28, 0x8e, 0x8b,
	0x0b, 0xe1, 0x1f, 0x21, 0x75, 0x3d, 0x6c, 0x61, 0xa4, 0x87, 0x11, 0x40, 0x52, 0xaa, 0x84, 0x15,
	0x82, 0xbc, 0xc1, 0x20, 0x14, 0xc1, 0xc5, 0x01, 0xf3, 0x99, 0x10, 0x0e, 0x4d, 0x68, 0x41, 0x24,
	0xa5, 0x4c, 0x48, 0x19, 0xc4, 0xe4, 0x32, 0x2e, 0x21, 0xcc, 0x50, 0x10, 0xd2, 0xc7, 0xae, 0x19,
	0x67, 0x60, 0x4a, 0xe9, 0x12, 0xaf, 0x01, 0x6c, 0xaf, 0x93, 0x0b, 0x97, 0x6a, 0x66, 0xbe, 0x1e,
	0x58, 0x51, 0x6a, 0x45, 0x62, 0x6e, 0x41, 0x4e, 0x6a, 0x31, 0x56, 0x23, 0x9c, 0x24, 0xd1, 0x03,
	0xdb, 0xbd, 0xa8, 0x20, 0x39, 0x00, 0x94, 0x14, 0x03, 0x18, 0x93, 0xd8, 0xc0, 0x69, 0xd2, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x02, 0xf0, 0xc1, 0xb4, 0xb4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WordSearchSystemClient is the client API for WordSearchSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WordSearchSystemClient interface {
	// Sends a greeting
	SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*SearchWordReply, error)
	AddWords(ctx context.Context, in *AddWordsRequest, opts ...grpc.CallOption) (*AddWordsReply, error)
	Top5SearchKeyWords(ctx context.Context, in *Top5SearchKeyWordsRequest, opts ...grpc.CallOption) (*Top5SearchKeyWordsReply, error)
}

type wordSearchSystemClient struct {
	cc *grpc.ClientConn
}

func NewWordSearchSystemClient(cc *grpc.ClientConn) WordSearchSystemClient {
	return &wordSearchSystemClient{cc}
}

func (c *wordSearchSystemClient) SearchWord(ctx context.Context, in *SearchWordRequest, opts ...grpc.CallOption) (*SearchWordReply, error) {
	out := new(SearchWordReply)
	err := c.cc.Invoke(ctx, "/wordsearchsystemgrpc.WordSearchSystem/SearchWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordSearchSystemClient) AddWords(ctx context.Context, in *AddWordsRequest, opts ...grpc.CallOption) (*AddWordsReply, error) {
	out := new(AddWordsReply)
	err := c.cc.Invoke(ctx, "/wordsearchsystemgrpc.WordSearchSystem/AddWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wordSearchSystemClient) Top5SearchKeyWords(ctx context.Context, in *Top5SearchKeyWordsRequest, opts ...grpc.CallOption) (*Top5SearchKeyWordsReply, error) {
	out := new(Top5SearchKeyWordsReply)
	err := c.cc.Invoke(ctx, "/wordsearchsystemgrpc.WordSearchSystem/Top5SearchKeyWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordSearchSystemServer is the server API for WordSearchSystem service.
type WordSearchSystemServer interface {
	// Sends a greeting
	SearchWord(context.Context, *SearchWordRequest) (*SearchWordReply, error)
	AddWords(context.Context, *AddWordsRequest) (*AddWordsReply, error)
	Top5SearchKeyWords(context.Context, *Top5SearchKeyWordsRequest) (*Top5SearchKeyWordsReply, error)
}

func RegisterWordSearchSystemServer(s *grpc.Server, srv WordSearchSystemServer) {
	s.RegisterService(&_WordSearchSystem_serviceDesc, srv)
}

func _WordSearchSystem_SearchWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchSystemServer).SearchWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordsearchsystemgrpc.WordSearchSystem/SearchWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchSystemServer).SearchWord(ctx, req.(*SearchWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordSearchSystem_AddWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchSystemServer).AddWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordsearchsystemgrpc.WordSearchSystem/AddWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchSystemServer).AddWords(ctx, req.(*AddWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WordSearchSystem_Top5SearchKeyWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Top5SearchKeyWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordSearchSystemServer).Top5SearchKeyWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wordsearchsystemgrpc.WordSearchSystem/Top5SearchKeyWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordSearchSystemServer).Top5SearchKeyWords(ctx, req.(*Top5SearchKeyWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WordSearchSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wordsearchsystemgrpc.WordSearchSystem",
	HandlerType: (*WordSearchSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchWord",
			Handler:    _WordSearchSystem_SearchWord_Handler,
		},
		{
			MethodName: "AddWords",
			Handler:    _WordSearchSystem_AddWords_Handler,
		},
		{
			MethodName: "Top5SearchKeyWords",
			Handler:    _WordSearchSystem_Top5SearchKeyWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "word_search_system_grpc.proto",
}
